name: Sample Ops Repo Skeleton
on:
  push:
    branches: [dev,pre-prod,prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: ./deploy.sh
      - uses: csviri/git-ops-actions-promote@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
