name: Sample CI Skeleton
on:
  push:
    branches: [ dev, pre-prod, prod ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./deploy.sh
      - uses: csviri/git-ops-actions-promote@0.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}


